/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeTester */

#ifndef _Included_NativeTester
#define _Included_NativeTester
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeTester
 * Method:    greeting
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_NativeTester_greeting
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
