include ../../setup_vars.mk


CPP_SRC_FILES=*.cpp
DEFAULT_TARGET_NAME=stlmain


all :
	$(CXX) $(CPP_SRC_FILES) $(CXXFLAGS) -o $(DEFAULT_TARGET_NAME)


include ../../run_target.mk


RUN_TARGET :
	$(CPP_DEFAULT_TARGET_NAME)